name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore and test backend
      run: |
        dotnet restore
        dotnet test tests/backend/unit/ea_Tracker.Tests.csproj --no-restore --verbosity normal

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        npm ci
        cd src/frontend && npm ci

    - name: Run frontend tests
      run: |
        npm run test:frontend -- --watchAll=false

    # E2E tests require running servers - commented out for CI
    # - name: Run E2E tests
    #   run: |
    #     npm run test:e2e
